In [42]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

In [43]:
energy_data = "Resources/Project_2_total_energy_consumption_monthly.csv"
energy_data = pd.read_csv(energy_data)
energy_data.head()

,MSN,YYYYMM,Value,Column_Order,Description,Unit,Right,Left,Converted Date
0,TETCBUS,198706,6.283858,12,Total Primary Energy Consumption,Quadrillion Btu,6,1987,Jun-87
1,TETCBUS,198707,6.630484,12,Total Primary Energy Consumption,Quadrillion Btu,7,1987,Jul-87
2,TETCBUS,198708,6.518294,12,Total Primary Energy Consumption,Quadrillion Btu,8,1987,Aug-87
3,TETCBUS,198709,6.127542,12,Total Primary Energy Consumption,Quadrillion Btu,9,1987,Sep-87
4,TETCBUS,198710,6.366409,12,Total Primary Energy Consumption,Quadrillion Btu,10,1987,Oct-87

In [44]:
energy_data = energy_data.rename(columns={"Right": "Month", "Left": "Year"})

In [45]:
energy_data.head()

,MSN,YYYYMM,Value,Column_Order,Description,Unit,Month,Year,Converted Date
0,TETCBUS,198706,6.283858,12,Total Primary Energy Consumption,Quadrillion Btu,6,1987,Jun-87
1,TETCBUS,198707,6.630484,12,Total Primary Energy Consumption,Quadrillion Btu,7,1987,Jul-87
2,TETCBUS,198708,6.518294,12,Total Primary Energy Consumption,Quadrillion Btu,8,1987,Aug-87
3,TETCBUS,198709,6.127542,12,Total Primary Energy Consumption,Quadrillion Btu,9,1987,Sep-87
4,TETCBUS,198710,6.366409,12,Total Primary Energy Consumption,Quadrillion Btu,10,1987,Oct-87

In [46]:
energy_data.dtypes

MSN                object
YYYYMM              int64
Value             float64
Column_Order        int64
Description        object
Unit               object
Month               int64
Year                int64
Converted Date     object
dtype: object

In [47]:
# set index for energy data 
energy_data["Date_Index"] = energy_data['Month'].map(str) +"-"+ energy_data['Year'].map(str)

In [48]:
investor_sentiment = "Resources/Project_2_investor_sentiment_USA.csv"
investor_sentiment = pd.read_csv(investor_sentiment)
investor_sentiment.head(100)

,Old Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,Unnamed: 13,coverted Date,Date
0,6/30/2018,0.284483,0.307471,0.408046,1.000000,0.368306,-0.123563,0.382716,0.484453,0.280978,2774.860000,2698.670000,2699.630000,NaN,18-Jun,18-Jun
1,5/31/2018,0.350181,0.386282,0.263538,1.000001,0.341175,0.086643,0.382716,0.484453,0.280978,2742.240000,2676.810000,2724.010000,NaN,18-May,18-May
2,4/30/2018,0.369085,0.375394,0.255521,1.000000,0.326363,0.113564,0.382716,0.484453,0.280978,2717.490000,2612.670000,2639.400000,NaN,18-Apr,18-Apr
3,3/31/2018,0.319361,0.327345,0.353293,0.999999,0.369871,-0.033932,0.382716,0.484453,0.280978,2739.140000,2585.890000,2605.000000,NaN,18-Mar,18-Mar
4,2/28/2018,0.446512,0.325581,0.227907,1.000000,0.478704,0.218605,0.382716,0.484453,0.280978,2754.420000,2637.080000,2701.330000,NaN,18-Feb,18-Feb
5,1/31/2018,0.454545,0.305195,0.240260,1.000000,0.491267,0.214285,0.382716,0.484453,0.280978,2852.970000,2778.380000,2837.540000,NaN,18-Jan,18-Jan
6,12/31/2017,0.526455,0.267196,0.206349,1.000000,0.413640,0.320106,0.382716,0.484453,0.280978,2694.440000,2676.110000,2682.620000,NaN,17-Dec,17-Dec
7,11/30/2017,0.359459,0.324324,0.316216,0.999999,0.385354,0.043243,0.382716,0.484453,0.280978,2634.890000,2589.170000,2626.070000,NaN,17-Nov,17-Nov
8,10/31/2017,0.396396,0.273273,0.330330,0.999999,0.371215,0.066066,0.382716,0.484453,0.280978,2578.290000,2544.000000,2557.150000,NaN,17-Oct,17-Oct
9,9/30/2017,0.333333,0.379310,0.287356,0.999999,0.331219,0.045977,0.382716,0.484453,0.280978,2511.750000,2488.030000,2507.040000,NaN,17-Sep,17-Sep
10,8/31/2017,0.250000,0.351064,0.398936,1.000000,0.319044,-0.148936,0.382716,0.484453,0.280978,2460.310000,2428.200000,2457.590000,NaN,17-Aug,17-Aug
11,7/31/2017,0.344595,0.412162,0.243243,1.000000,0.322291,0.101352,0.382768,0.484584,0.280953,2481.690000,2463.850000,2477.830000,NaN,17-Jul,17-Jul
12,6/30/2017,0.297143,0.434286,0.268571,1.000000,0.308048,0.028572,0.382749,0.484665,0.280832,2450.420000,2419.380000,2440.690000,NaN,17-Jun,17-Jun
13,5/31/2017,0.328571,0.371429,0.300000,1.000000,0.310680,0.028571,0.382895,0.484923,0.280866,2405.580000,2352.720000,2404.390000,NaN,17-May,17-May
14,4/30/2017,0.380488,0.302439,0.317073,1.000000,0.309618,0.063415,0.382988,0.485074,0.280903,2398.160000,2335.050000,2387.450000,NaN,17-Apr,17-Apr
15,3/31/2017,0.302181,0.323988,0.373832,1.000001,0.339911,-0.071651,0.382963,0.485159,0.280767,2363.780000,2322.250000,2361.130000,NaN,17-Mar,17-Mar
16,2/28/2017,0.384615,0.292308,0.323077,1.000000,0.373221,0.061538,0.383077,0.485394,0.280759,2366.710000,2322.170000,2362.820000,NaN,17-Feb,17-Feb
17,1/31/2017,0.315789,0.349282,0.334928,0.999999,0.420473,-0.019139,0.383265,0.485631,0.280898,2299.550000,2257.020000,2298.370000,NaN,17-Jan,17-Jan
18,12/31/2016,0.455696,0.286920,0.257384,1.000000,0.446457,0.198312,0.383316,0.485754,0.280877,2273.820000,2249.110000,2249.920000,NaN,16-Dec,16-Dec
19,11/30/2016,0.498938,0.280255,0.220807,1.000000,0.327291,0.278131,0.383075,0.485537,0.280613,2204.800000,2172.200000,2204.720000,NaN,16-Nov,16-Nov
20,10/31/2016,0.247549,0.411765,0.340686,1.000000,0.261589,-0.093137,0.382707,0.485014,0.280400,2154.790039,2130.090088,2139.429932,NaN,16-Oct,16-Oct
21,9/30/2016,0.240000,0.388889,0.371111,1.000000,0.289241,-0.131111,0.382706,0.485123,0.280288,2179.989990,2139.570068,2171.370117,NaN,16-Sep,16-Sep
22,8/31/2016,0.294243,0.409382,0.296375,1.000000,0.325835,-0.002132,0.382669,0.485195,0.280143,2193.420000,2168.500000,2175.440000,NaN,16-Aug,16-Aug
23,7/31/2016,0.312500,0.403409,0.284091,1.000000,0.298325,0.028409,0.382696,0.485341,0.280051,2175.629883,2159.070068,2166.580078,NaN,16-Jul,16-Jul
24,6/30/2016,0.289125,0.376658,0.334218,1.000001,0.239658,-0.045093,0.382884,0.485545,0.280223,2113.320000,1991.680000,2070.770000,NaN,16-Jun,16-Jun
25,5/31/2016,0.177515,0.528600,0.293886,1.000001,0.250800,-0.116371,0.382996,0.485801,0.280192,2094.729980,2025.910034,2090.540039,NaN,16-May,16-May
26,4/30/2016,0.273663,0.440329,0.286008,1.000000,0.311361,-0.012345,0.383208,0.486056,0.280360,2111.050049,2077.520020,2095.149902,NaN,16-Apr,16-Apr
27,3/31/2016,0.271805,0.470588,0.257606,0.999999,0.297859,0.014199,0.383374,0.486290,0.280458,2072.209961,2022.489990,2063.949951,NaN,16-Mar,16-Mar
28,2/29/2016,0.311947,0.373894,0.314159,1.000000,0.246110,-0.002212,0.383588,0.486545,0.280632,1946.700000,1871.440000,1929.800000,NaN,16-Feb,16-Feb
29,1/31/2016,0.297535,0.302817,0.399648,1.000000,0.243966,-0.102113,0.383787,0.486793,0.280781,1916.990000,1812.290000,1882.950000,NaN,16-Jan,16-Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,8/31/2012,0.347222,0.326389,0.326389,1.000000,0.326214,0.020833,0.384907,0.488293,0.281522,1426.680000,1398.040000,1410.490000,NaN,12-Aug,12-Aug
71,7/31/2012,0.281150,0.287540,0.431310,1.000000,0.295269,-0.150160,0.384907,0.488293,0.281522,1380.390000,1329.240000,1337.890000,NaN,12-Jul,12-Jul
72,6/30/2012,0.286689,0.269625,0.443686,1.000000,0.288136,-0.156997,0.384907,0.488293,0.281522,1363.460000,1309.270000,1331.850000,NaN,12-Jun,12-Jun
73,5/31/2012,0.280156,0.299611,0.420233,1.000000,0.287280,-0.140077,0.384907,0.488293,0.281522,1334.930000,1295.730000,1313.320000,NaN,12-May,12-May
74,4/30/2012,0.276423,0.349593,0.373984,1.000000,0.372467,-0.097561,0.384907,0.488293,0.281522,1392.760000,1358.790000,1390.690000,NaN,12-Apr,12-Apr
75,3/31/2012,0.424700,0.320500,0.254800,1.000000,0.444246,0.169900,0.384907,0.488293,0.281522,1419.150000,1386.870000,1405.540000,NaN,12-Mar,12-Mar
76,2/29/2012,0.436890,0.288020,0.275080,0.999990,0.469373,0.161810,0.384907,0.488293,0.281522,1367.760000,1340.800000,1357.660000,NaN,12-Feb,12-Feb
77,1/31/2012,0.483974,0.326920,0.189100,0.999994,0.433403,0.294874,0.384907,0.488293,0.281522,1328.300000,1290.220000,1326.060000,NaN,12-Jan,12-Jan
78,12/31/2011,0.406000,0.285700,0.308270,0.999970,0.381856,0.097730,0.384907,0.488293,0.281522,1269.370000,1202.370000,1249.640000,NaN,11-Dec,11-Dec
79,11/30/2011,0.327100,0.290100,0.382700,0.999900,0.391912,-0.055600,0.384907,0.488293,0.281522,1259.610000,1158.660000,1158.670000,NaN,11-Nov,11-Nov
80,10/31/2011,0.430000,0.320000,0.250000,1.000000,0.340675,0.180000,0.384907,0.488293,0.281522,1256.550000,1191.480000,1242.000000,NaN,11-Oct,11-Oct
81,9/30/2011,0.325100,0.206800,0.467900,0.999800,0.328263,-0.142800,0.384907,0.488293,0.281522,1220.390000,1114.220000,1151.060000,NaN,11-Sep,11-Sep
82,8/31/2011,0.364400,0.226000,0.409600,1.000000,0.364212,-0.045200,0.384907,0.488293,0.281522,1190.680000,1121.090000,1159.270000,NaN,11-Aug,11-Aug
83,7/31/2011,0.378400,0.307400,0.314200,1.000000,0.359963,0.064200,0.384907,0.488293,0.281522,1347.000000,1303.490000,1304.890000,NaN,11-Jul,11-Jul
84,6/30/2011,0.383100,0.314900,0.301900,0.999900,0.303050,0.081200,0.384907,0.488293,0.281522,1309.210000,1296.850000,1307.410000,NaN,11-Jun,11-Jun
85,5/31/2011,0.256100,0.329700,0.414200,1.000000,0.343037,-0.158100,0.384907,0.488293,0.281522,1346.820000,1336.360000,1343.600000,NaN,11-May,11-May
86,4/30/2011,0.379000,0.314500,0.306500,1.000000,0.374887,0.072500,0.384907,0.488293,0.281522,1349.550000,1336.750000,1347.240000,NaN,11-Apr,11-Apr
87,3/31/2011,0.418100,0.271200,0.310700,1.000000,0.391763,0.107400,0.384907,0.488293,0.281522,1331.740000,1321.890000,1328.260000,NaN,11-Mar,11-Mar
88,2/28/2011,0.366300,0.272300,0.361400,1.000000,0.481450,0.004900,0.384907,0.488293,0.281522,1344.070000,1338.120000,1343.010000,NaN,11-Feb,11-Feb
89,1/31/2011,0.420400,0.236700,0.342900,1.000000,0.523975,0.077500,0.384907,0.488293,0.281522,1299.740000,1291.970000,1296.630000,NaN,11-Jan,11-Jan
90,12/31/2010,0.516100,0.283400,0.200500,1.000000,0.515988,0.315600,0.384907,0.488293,0.281522,1262.600000,1258.780000,1259.780000,NaN,10-Dec,10-Dec
91,11/30/2010,0.474000,0.279200,0.246800,1.000000,0.487712,0.227200,0.384907,0.488293,0.281522,1200.290000,1198.350000,1199.730000,NaN,10-Nov,10-Nov
92,10/31/2010,0.512300,0.271600,0.216000,0.999900,0.474050,0.296300,0.384907,0.488293,0.281522,1189.530000,1184.470000,1182.450000,NaN,10-Oct,10-Oct
93,9/30/2010,0.425300,0.258600,0.316100,1.000000,0.379588,0.109200,0.384907,0.488293,0.281522,1157.160000,1145.970000,1144.730000,NaN,10-Sep,10-Sep
94,8/31/2010,0.207400,0.297900,0.494700,1.000000,0.316837,-0.287300,0.384907,0.488293,0.281522,1060.250000,1055.380000,1055.330000,NaN,10-Aug,10-Aug
95,7/31/2010,0.400000,0.266700,0.333300,1.000000,0.335675,0.066700,0.384907,0.488293,0.281522,1115.900000,1109.630000,1106.130000,NaN,10-Jul,10-Jul
96,6/30/2010,0.344600,0.331100,0.324300,1.000000,0.369175,0.020300,0.384907,0.488293,0.281522,1090.930000,1079.170000,1092.040000,NaN,10-Jun,10-Jun
97,5/31/2010,0.298300,0.193000,0.508800,1.000100,0.397100,-0.210500,0.384907,0.488293,0.281522,1089.600000,1074.270000,1067.950000,NaN,10-May,10-May
98,4/30/2010,0.413600,0.300000,0.286400,1.000000,0.406463,0.127200,0.384907,0.488293,0.281522,1202.590000,1193.300000,1191.360000,NaN,10-Apr,10-Apr
99,3/31/2010,0.323900,0.329500,0.346600,1.000000,0.357038,-0.022700,0.384907,0.488293,0.281522,1176.710000,1170.030000,1167.720000,NaN,10-Mar,10-Mar

In [49]:
# Remake columns for dates of investor data 
# format as date
investor_sentiment['New Date'] = pd.to_datetime(investor_sentiment["Old Date"])

In [50]:
# Create year, month columns
# Create date index
investor_sentiment['Year'], investor_sentiment['Month'] = investor_sentiment['New Date'].dt.year, investor_sentiment['New Date'].dt.month

In [51]:
# create year-month index combo for investor sentiment
investor_sentiment["Date_Index"] = investor_sentiment['Month'].map(str) +"-"+ investor_sentiment['Year'].map(str)

In [52]:
investor_sentiment.head()

,Old Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,Unnamed: 13,coverted Date,Date,New Date,Year,Month,Date_Index
0,6/30/2018,0.284483,0.307471,0.408046,1.000000,0.368306,-0.123563,0.382716,0.484453,0.280978,2774.86,2698.67,2699.63,NaN,18-Jun,18-Jun,2018-06-30,2018,6,6-2018
1,5/31/2018,0.350181,0.386282,0.263538,1.000001,0.341175,0.086643,0.382716,0.484453,0.280978,2742.24,2676.81,2724.01,NaN,18-May,18-May,2018-05-31,2018,5,5-2018
2,4/30/2018,0.369085,0.375394,0.255521,1.000000,0.326363,0.113564,0.382716,0.484453,0.280978,2717.49,2612.67,2639.40,NaN,18-Apr,18-Apr,2018-04-30,2018,4,4-2018
3,3/31/2018,0.319361,0.327345,0.353293,0.999999,0.369871,-0.033932,0.382716,0.484453,0.280978,2739.14,2585.89,2605.00,NaN,18-Mar,18-Mar,2018-03-31,2018,3,3-2018
4,2/28/2018,0.446512,0.325581,0.227907,1.000000,0.478704,0.218605,0.382716,0.484453,0.280978,2754.42,2637.08,2701.33,NaN,18-Feb,18-Feb,2018-02-28,2018,2,2-2018

In [53]:
investor_sentiment.dtypes

Old Date                             object
Bullish                             float64
Neutral                             float64
Bearish                             float64
Total                               float64
Bullish 8-Week Mov Avg              float64
Bull-Bear Spread                    float64
Bullish Average                     float64
Bullish Average + St. Dev           float64
Bullish Average - St. Dev           float64
S&P 500 Weekly High                 float64
S&P 500 Weekly Low                  float64
S&P 500 Weekly Close                float64
Unnamed: 13                         float64
coverted Date                        object
Date                                 object
New Date                     datetime64[ns]
Year                                  int64
Month                                 int64
Date_Index                           object
dtype: object

In [54]:
energy_data.head()

,MSN,YYYYMM,Value,Column_Order,Description,Unit,Month,Year,Converted Date,Date_Index
0,TETCBUS,198706,6.283858,12,Total Primary Energy Consumption,Quadrillion Btu,6,1987,Jun-87,6-1987
1,TETCBUS,198707,6.630484,12,Total Primary Energy Consumption,Quadrillion Btu,7,1987,Jul-87,7-1987
2,TETCBUS,198708,6.518294,12,Total Primary Energy Consumption,Quadrillion Btu,8,1987,Aug-87,8-1987
3,TETCBUS,198709,6.127542,12,Total Primary Energy Consumption,Quadrillion Btu,9,1987,Sep-87,9-1987
4,TETCBUS,198710,6.366409,12,Total Primary Energy Consumption,Quadrillion Btu,10,1987,Oct-87,10-1987

In [55]:
# rename columns  for energy data
energy_data = energy_data.rename(columns={"Value": "Total Primary Energy Consumption (Quadrillion BTUs)"})

In [56]:
# drop columns for energy data 
energy_data_refined = energy_data.drop(columns=["MSN", "YYYYMM", "Column_Order", "Unit", "Year", "Month", "Description", "Converted Date"])

In [57]:
# set index for energy data
energy_indexed= energy_data_refined.set_index("Date_Index")
energy_indexed.head()

            Total Primary Energy Consumption (Quadrillion BTUs)
Date_Index
6-1987                                               6.283858
7-1987                                               6.630484
8-1987                                               6.518294
9-1987                                               6.127542
10-1987                                              6.366409

In [58]:
# drop columns for investor data

investor_sentiment_refined = investor_sentiment.drop(columns=["Old Date", "Total", "Bullish 8-Week Mov Avg", "Bullish Average", "Bullish Average + St. Dev", "Bullish Average - St. Dev", "S&P 500 Weekly High", "S&P 500 Weekly Low", "Unnamed: 13"])

In [59]:
# rename columns for investor data
investor_sentiment_renamed =investor_sentiment_refined.rename(columns={"Bullish": "Bullish Sentiment", "Neutral": "Neutral Sentiment", "Bearish": "Bearish Sentiment", "coverted Date": "Date"})

In [60]:
# set index for investor data

investor_indexed = investor_sentiment_renamed.set_index("Date_Index")
investor_indexed.head()

,Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Date,Date,New Date,Year,Month
Date_Index,,,,,,,,,,
6-2018,0.284483,0.307471,0.408046,-0.123563,2699.63,18-Jun,18-Jun,2018-06-30,2018,6
5-2018,0.350181,0.386282,0.263538,0.086643,2724.01,18-May,18-May,2018-05-31,2018,5
4-2018,0.369085,0.375394,0.255521,0.113564,2639.40,18-Apr,18-Apr,2018-04-30,2018,4
3-2018,0.319361,0.327345,0.353293,-0.033932,2605.00,18-Mar,18-Mar,2018-03-31,2018,3
2-2018,0.446512,0.325581,0.227907,0.218605,2701.33,18-Feb,18-Feb,2018-02-28,2018,2

In [61]:
# merge data sets on date index 
merged_data = pd.DataFrame.merge(energy_indexed, investor_indexed, on="Date_Index")
merged_data.head(20)
#merged_data

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Date,Date,New Date,Year,Month
Date_Index,,,,,,,,,,,
6-1987,6.283858,NaN,NaN,NaN,NaN,NaN,Jun-87,1-Jun,1987-06-30,1987,6
7-1987,6.630484,0.26,0.48,0.26,0.00,318.66,Jul-87,1-Jul,1987-07-31,1987,7
8-1987,6.518294,0.52,0.18,0.30,0.22,323.04,Aug-87,1-Aug,1987-08-31,1987,8
9-1987,6.127542,0.53,0.17,0.30,0.23,320.16,Sep-87,1-Sep,1987-09-30,1987,9
10-1987,6.366409,0.44,0.23,0.33,0.11,251.79,Oct-87,1-Oct,1987-10-31,1987,10
11-1987,6.346123,0.27,0.46,0.27,0.00,240.34,Nov-87,1-Nov,1987-11-30,1987,11
12-1987,7.281541,0.25,0.49,0.26,-0.01,247.08,Dec-87,1-Dec,1987-12-31,1987,12
1-1988,7.804136,0.26,0.45,0.29,-0.03,257.07,Jan-88,1-Jan,1988-01-31,1988,1
2-1988,7.311849,0.30,0.51,0.19,0.11,262.46,Feb-88,1-Feb,1988-02-29,1988,2
3-1988,7.300926,0.45,0.38,0.17,0.28,258.51,Mar-88,1-Mar,1988-03-31,1988,3
4-1988,6.453888,0.22,0.48,0.30,-0.08,261.33,Apr-88,1-Apr,1988-04-30,1988,4
5-1988,6.394683,0.28,0.52,0.20,0.08,253.42,May-88,1-May,1988-05-31,1988,5
6-1988,6.511855,0.33,0.44,0.23,0.10,273.78,Jun-88,1-Jun,1988-06-30,1988,6
7-1988,6.750241,0.23,0.54,0.23,0.00,272.02,Jul-88,1-Jul,1988-07-31,1988,7
8-1988,6.992534,0.28,0.40,0.32,-0.04,259.68,Aug-88,1-Aug,1988-08-31,1988,8
9-1988,6.344903,0.26,0.44,0.30,-0.04,271.91,Sep-88,1-Sep,1988-09-30,1988,9
10-1988,6.591078,0.40,0.38,0.22,0.18,278.53,Oct-88,1-Oct,1988-10-31,1988,10
11-1988,6.708190,0.17,0.44,0.39,-0.22,267.23,Nov-88,1-Nov,1988-11-30,1988,11
12-1988,7.544911,0.24,0.54,0.22,0.02,277.72,Dec-88,1-Dec,1988-12-31,1988,12
1-1989,7.643419,0.32,0.49,0.19,0.13,293.82,Jan-89,1-Jan,1989-01-31,1989,1

In [62]:
merged_data.describe()

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Year,Month
count,373.000000,372.000000,372.000000,372.000000,372.000000,372.000000,373.000000,373.00000
mean,7.850449,0.385664,0.312137,0.302196,0.083468,1114.300242,2002.458445,6.49866
std,0.681195,0.101233,0.082521,0.095346,0.178518,606.682673,8.994115,3.45215
min,6.127542,0.170000,0.106700,0.066700,-0.380000,240.340000,1987.000000,1.00000
25%,7.471880,0.308196,0.257675,0.229875,-0.042548,511.210000,1995.000000,4.00000
50%,7.809119,0.380000,0.312250,0.296409,0.075600,1123.905000,2002.000000,6.00000
75%,8.312785,0.450000,0.370000,0.364741,0.210000,1399.082500,2010.000000,9.00000
max,9.668643,0.714300,0.540000,0.610000,0.628600,2837.540000,2018.000000,12.00000

In [63]:
merged_data.dtypes

Total Primary Energy Consumption (Quadrillion BTUs)           float64
Bullish Sentiment                                             float64
Neutral Sentiment                                             float64
Bearish Sentiment                                             float64
Bull-Bear Spread                                              float64
S&P 500 Weekly Close                                          float64
Date                                                           object
Date                                                           object
New Date                                               datetime64[ns]
Year                                                            int64
Month                                                           int64
dtype: object

merged_data_df = pd.DataFrame(merged_data)
print (merged_data)

In [64]:
# drop columns for merged data

merged_data = merged_data.drop(columns=["New Date"])

In [65]:
print (merged_data)

            Total Primary Energy Consumption (Quadrillion BTUs)  \
Date_Index
6-1987                                               6.283858
7-1987                                               6.630484
8-1987                                               6.518294
9-1987                                               6.127542
10-1987                                              6.366409
11-1987                                              6.346123
12-1987                                              7.281541
1-1988                                               7.804136
2-1988                                               7.311849
3-1988                                               7.300926
4-1988                                               6.453888
5-1988                                               6.394683
6-1988                                               6.511855
7-1988                                               6.750241
8-1988                                               6.992534
9-1988                                               6.344903
10-1988                                              6.591078
11-1988                                              6.708190
12-1988                                              7.544911
1-1989                                               7.643419
2-1989                                               7.233498
3-1989                                               7.545703
4-1989                                               6.664216
5-1989                                               6.639140
6-1989                                               6.697346
7-1989                                               6.859659
8-1989                                               7.031494
9-1989                                               6.484541
10-1989                                              6.794031
11-1989                                              6.943560
...                                                       ...
1-2016                                               9.064412
2-2016                                               8.237571
3-2016                                               7.992649
4-2016                                               7.458301
5-2016                                               7.594760
6-2016                                               7.945396
7-2016                                               8.485410
8-2016                                               8.553543
9-2016                                               7.762231
10-2016                                              7.664109
11-2016                                              7.728924
12-2016                                              9.094618
1-2017                                               8.987299
2-2017                                               7.633252
3-2017                                               8.458327
4-2017                                               7.461829
5-2017                                               7.818154
6-2017                                               7.980952
7-2017                                               8.429013
8-2017                                               8.313658
9-2017                                               7.638135
10-2017                                              7.839891
11-2017                                              8.111326
12-2017                                              9.196654
1-2018                                               9.668643
2-2018                                               8.048857
3-2018                                               8.676000
4-2018                                               7.895465
5-2018                                               8.017006
6-2018                                               8.157678

            Bullish Sentiment  Neutral Sentiment  Bearish Sentiment  \
Date_Index
6-1987                    NaN                NaN                NaN
7-1987               0.260000           0.480000           0.260000
8-1987               0.520000           0.180000           0.300000
9-1987               0.530000           0.170000           0.300000
10-1987              0.440000           0.230000           0.330000
11-1987              0.270000           0.460000           0.270000
12-1987              0.250000           0.490000           0.260000
1-1988               0.260000           0.450000           0.290000
2-1988               0.300000           0.510000           0.190000
3-1988               0.450000           0.380000           0.170000
4-1988               0.220000           0.480000           0.300000
5-1988               0.280000           0.520000           0.200000
6-1988               0.330000           0.440000           0.230000
7-1988               0.230000           0.540000           0.230000
8-1988               0.280000           0.400000           0.320000
9-1988               0.260000           0.440000           0.300000
10-1988              0.400000           0.380000           0.220000
11-1988              0.170000           0.440000           0.390000
12-1988              0.240000           0.540000           0.220000
1-1989               0.320000           0.490000           0.190000
2-1989               0.290000           0.450000           0.260000
3-1989               0.180000           0.420000           0.400000
4-1989               0.310000           0.400000           0.290000
5-1989               0.480000           0.310000           0.210000
6-1989               0.400000           0.340000           0.260000
7-1989               0.410000           0.250000           0.340000
8-1989               0.450000           0.240000           0.310000
9-1989               0.330000           0.380000           0.290000
10-1989              0.360000           0.330000           0.310000
11-1989              0.270000           0.400000           0.330000
...                       ...                ...                ...
1-2016               0.297535           0.302817           0.399648
2-2016               0.311947           0.373894           0.314159
3-2016               0.271805           0.470588           0.257606
4-2016               0.273663           0.440329           0.286008
5-2016               0.177515           0.528600           0.293886
6-2016               0.289125           0.376658           0.334218
7-2016               0.312500           0.403409           0.284091
8-2016               0.294243           0.409382           0.296375
9-2016               0.240000           0.388889           0.371111
10-2016              0.247549           0.411765           0.340686
11-2016              0.498938           0.280255           0.220807
12-2016              0.455696           0.286920           0.257384
1-2017               0.315789           0.349282           0.334928
2-2017               0.384615           0.292308           0.323077
3-2017               0.302181           0.323988           0.373832
4-2017               0.380488           0.302439           0.317073
5-2017               0.328571           0.371429           0.300000
6-2017               0.297143           0.434286           0.268571
7-2017               0.344595           0.412162           0.243243
8-2017               0.250000           0.351064           0.398936
9-2017               0.333333           0.379310           0.287356
10-2017              0.396396           0.273273           0.330330
11-2017              0.359459           0.324324           0.316216
12-2017              0.526455           0.267196           0.206349
1-2018               0.454545           0.305195           0.240260
2-2018               0.446512           0.325581           0.227907
3-2018               0.319361           0.327345           0.353293
4-2018               0.369085           0.375394           0.255521
5-2018               0.350181           0.386282           0.263538
6-2018               0.284483           0.307471           0.408046

            Bull-Bear Spread  S&P 500 Weekly Close    Date    Date  Year  \
Date_Index
6-1987                   NaN                   NaN  Jun-87   1-Jun  1987
7-1987              0.000000            318.660000  Jul-87   1-Jul  1987
8-1987              0.220000            323.040000  Aug-87   1-Aug  1987
9-1987              0.230000            320.160000  Sep-87   1-Sep  1987
10-1987             0.110000            251.790000  Oct-87   1-Oct  1987
11-1987             0.000000            240.340000  Nov-87   1-Nov  1987
12-1987            -0.010000            247.080000  Dec-87   1-Dec  1987
1-1988             -0.030000            257.070000  Jan-88   1-Jan  1988
2-1988              0.110000            262.460000  Feb-88   1-Feb  1988
3-1988              0.280000            258.510000  Mar-88   1-Mar  1988
4-1988             -0.080000            261.330000  Apr-88   1-Apr  1988
5-1988              0.080000            253.420000  May-88   1-May  1988
6-1988              0.100000            273.780000  Jun-88   1-Jun  1988
7-1988              0.000000            272.020000  Jul-88   1-Jul  1988
8-1988             -0.040000            259.680000  Aug-88   1-Aug  1988
9-1988             -0.040000            271.910000  Sep-88   1-Sep  1988
10-1988             0.180000            278.530000  Oct-88   1-Oct  1988
11-1988            -0.220000            267.230000  Nov-88   1-Nov  1988
12-1988             0.020000            277.720000  Dec-88   1-Dec  1988
1-1989              0.130000            293.820000  Jan-89   1-Jan  1989
2-1989              0.030000            287.130000  Feb-89   1-Feb  1989
3-1989             -0.220000            294.870000  Mar-89   1-Mar  1989
4-1989              0.020000            309.640000  Apr-89   1-Apr  1989
5-1989              0.270000            321.590000  May-89   1-May  1989
6-1989              0.140000            317.980000  Jun-89   1-Jun  1989
7-1989              0.070000            342.150000  Jul-89   1-Jul  1989
8-1989              0.140000            350.520000  Aug-89   1-Aug  1989
9-1989              0.040000            349.150000  Sep-89   1-Sep  1989
10-1989             0.050000            335.060000  Oct-89   1-Oct  1989
11-1989            -0.060000            343.970000  Nov-89   1-Nov  1989
...                      ...                   ...     ...     ...   ...
1-2016             -0.102113           1882.950000  16-Jan  16-Jan  2016
2-2016             -0.002212           1929.800000  16-Feb  16-Feb  2016
3-2016              0.014199           2063.949951  16-Mar  16-Mar  2016
4-2016             -0.012345           2095.149902  16-Apr  16-Apr  2016
5-2016             -0.116371           2090.540039  16-May  16-May  2016
6-2016             -0.045093           2070.770000  16-Jun  16-Jun  2016
7-2016              0.028409           2166.580078  16-Jul  16-Jul  2016
8-2016             -0.002132           2175.440000  16-Aug  16-Aug  2016
9-2016             -0.131111           2171.370117  16-Sep  16-Sep  2016
10-2016            -0.093137           2139.429932  16-Oct  16-Oct  2016
11-2016             0.278131           2204.720000  16-Nov  16-Nov  2016
12-2016             0.198312           2249.920000  16-Dec  16-Dec  2016
1-2017             -0.019139           2298.370000  17-Jan  17-Jan  2017
2-2017              0.061538           2362.820000  17-Feb  17-Feb  2017
3-2017             -0.071651           2361.130000  17-Mar  17-Mar  2017
4-2017              0.063415           2387.450000  17-Apr  17-Apr  2017
5-2017              0.028571           2404.390000  17-May  17-May  2017
6-2017              0.028572           2440.690000  17-Jun  17-Jun  2017
7-2017              0.101352           2477.830000  17-Jul  17-Jul  2017
8-2017             -0.148936           2457.590000  17-Aug  17-Aug  2017
9-2017              0.045977           2507.040000  17-Sep  17-Sep  2017
10-2017             0.066066           2557.150000  17-Oct  17-Oct  2017
11-2017             0.043243           2626.070000  17-Nov  17-Nov  2017
12-2017             0.320106           2682.620000  17-Dec  17-Dec  2017
1-2018              0.214285           2837.540000  18-Jan  18-Jan  2018
2-2018              0.218605           2701.330000  18-Feb  18-Feb  2018
3-2018             -0.033932           2605.000000  18-Mar  18-Mar  2018
4-2018              0.113564           2639.400000  18-Apr  18-Apr  2018
5-2018              0.086643           2724.010000  18-May  18-May  2018
6-2018             -0.123563           2699.630000  18-Jun  18-Jun  2018

            Month
Date_Index
6-1987          6
7-1987          7
8-1987          8
9-1987          9
10-1987        10
11-1987        11
12-1987        12
1-1988          1
2-1988          2
3-1988          3
4-1988          4
5-1988          5
6-1988          6
7-1988          7
8-1988          8
9-1988          9
10-1988        10
11-1988        11
12-1988        12
1-1989          1
2-1989          2
3-1989          3
4-1989          4
5-1989          5
6-1989          6
7-1989          7
8-1989          8
9-1989          9
10-1989        10
11-1989        11
...           ...
1-2016          1
2-2016          2
3-2016          3
4-2016          4
5-2016          5
6-2016          6
7-2016          7
8-2016          8
9-2016          9
10-2016        10
11-2016        11
12-2016        12
1-2017          1
2-2017          2
3-2017          3
4-2017          4
5-2017          5
6-2017          6
7-2017          7
8-2017          8
9-2017          9
10-2017        10
11-2017        11
12-2017        12
1-2018          1
2-2018          2
3-2018          3
4-2018          4
5-2018          5
6-2018          6

[373 rows x 10 columns]

In [66]:
#merged_drop_columns =merged_data.drop(columns=["Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17", "Year", "Month"])
#merged_final = merged_drop_columns.drop(["6-1987"])

#merged_final = merged_data
#merged_final.to_csv('merged_final.csv')

merged_drop_columns = merged_data.drop(columns=["Date", "Date", "Year", "Month"])
merged_final = merged_drop_columns.drop(["6-1987"])
merged_final

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close
Date_Index,,,,,,
7-1987,6.630484,0.260000,0.480000,0.260000,0.000000,318.660000
8-1987,6.518294,0.520000,0.180000,0.300000,0.220000,323.040000
9-1987,6.127542,0.530000,0.170000,0.300000,0.230000,320.160000
10-1987,6.366409,0.440000,0.230000,0.330000,0.110000,251.790000
11-1987,6.346123,0.270000,0.460000,0.270000,0.000000,240.340000
12-1987,7.281541,0.250000,0.490000,0.260000,-0.010000,247.080000
1-1988,7.804136,0.260000,0.450000,0.290000,-0.030000,257.070000
2-1988,7.311849,0.300000,0.510000,0.190000,0.110000,262.460000
3-1988,7.300926,0.450000,0.380000,0.170000,0.280000,258.510000
4-1988,6.453888,0.220000,0.480000,0.300000,-0.080000,261.330000
5-1988,6.394683,0.280000,0.520000,0.200000,0.080000,253.420000
6-1988,6.511855,0.330000,0.440000,0.230000,0.100000,273.780000
7-1988,6.750241,0.230000,0.540000,0.230000,0.000000,272.020000
8-1988,6.992534,0.280000,0.400000,0.320000,-0.040000,259.680000
9-1988,6.344903,0.260000,0.440000,0.300000,-0.040000,271.910000
10-1988,6.591078,0.400000,0.380000,0.220000,0.180000,278.530000
11-1988,6.708190,0.170000,0.440000,0.390000,-0.220000,267.230000
12-1988,7.544911,0.240000,0.540000,0.220000,0.020000,277.720000
1-1989,7.643419,0.320000,0.490000,0.190000,0.130000,293.820000
2-1989,7.233498,0.290000,0.450000,0.260000,0.030000,287.130000
3-1989,7.545703,0.180000,0.420000,0.400000,-0.220000,294.870000
4-1989,6.664216,0.310000,0.400000,0.290000,0.020000,309.640000
5-1989,6.639140,0.480000,0.310000,0.210000,0.270000,321.590000
6-1989,6.697346,0.400000,0.340000,0.260000,0.140000,317.980000
7-1989,6.859659,0.410000,0.250000,0.340000,0.070000,342.150000
8-1989,7.031494,0.450000,0.240000,0.310000,0.140000,350.520000
9-1989,6.484541,0.330000,0.380000,0.290000,0.040000,349.150000
10-1989,6.794031,0.360000,0.330000,0.310000,0.050000,335.060000
11-1989,6.943560,0.270000,0.400000,0.330000,-0.060000,343.970000
12-1989,8.248724,0.350000,0.310000,0.340000,0.010000,353.400000
...,...,...,...,...,...,...
1-2016,9.064412,0.297535,0.302817,0.399648,-0.102113,1882.950000
2-2016,8.237571,0.311947,0.373894,0.314159,-0.002212,1929.800000
3-2016,7.992649,0.271805,0.470588,0.257606,0.014199,2063.949951
4-2016,7.458301,0.273663,0.440329,0.286008,-0.012345,2095.149902
5-2016,7.594760,0.177515,0.528600,0.293886,-0.116371,2090.540039
6-2016,7.945396,0.289125,0.376658,0.334218,-0.045093,2070.770000
7-2016,8.485410,0.312500,0.403409,0.284091,0.028409,2166.580078
8-2016,8.553543,0.294243,0.409382,0.296375,-0.002132,2175.440000
9-2016,7.762231,0.240000,0.388889,0.371111,-0.131111,2171.370117
10-2016,7.664109,0.247549,0.411765,0.340686,-0.093137,2139.429932
11-2016,7.728924,0.498938,0.280255,0.220807,0.278131,2204.720000
12-2016,9.094618,0.455696,0.286920,0.257384,0.198312,2249.920000
1-2017,8.987299,0.315789,0.349282,0.334928,-0.019139,2298.370000
2-2017,7.633252,0.384615,0.292308,0.323077,0.061538,2362.820000
3-2017,8.458327,0.302181,0.323988,0.373832,-0.071651,2361.130000
4-2017,7.461829,0.380488,0.302439,0.317073,0.063415,2387.450000
5-2017,7.818154,0.328571,0.371429,0.300000,0.028571,2404.390000
6-2017,7.980952,0.297143,0.434286,0.268571,0.028572,2440.690000
7-2017,8.429013,0.344595,0.412162,0.243243,0.101352,2477.830000
8-2017,8.313658,0.250000,0.351064,0.398936,-0.148936,2457.590000
9-2017,7.638135,0.333333,0.379310,0.287356,0.045977,2507.040000
10-2017,7.839891,0.396396,0.273273,0.330330,0.066066,2557.150000
11-2017,8.111326,0.359459,0.324324,0.316216,0.043243,2626.070000
12-2017,9.196654,0.526455,0.267196,0.206349,0.320106,2682.620000
1-2018,9.668643,0.454545,0.305195,0.240260,0.214285,2837.540000
2-2018,8.048857,0.446512,0.325581,0.227907,0.218605,2701.330000
3-2018,8.676000,0.319361,0.327345,0.353293,-0.033932,2605.000000
4-2018,7.895465,0.369085,0.375394,0.255521,0.113564,2639.400000
5-2018,8.017006,0.350181,0.386282,0.263538,0.086643,2724.010000
6-2018,8.157678,0.284483,0.307471,0.408046,-0.123563,2699.630000

In [72]:
merged_df = pd.DataFrame(merged_final)

In [73]:
merged_df.head()

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close
Date_Index,,,,,,
7-1987,6.630484,0.26,0.48,0.26,0.00,318.66
8-1987,6.518294,0.52,0.18,0.30,0.22,323.04
9-1987,6.127542,0.53,0.17,0.30,0.23,320.16
10-1987,6.366409,0.44,0.23,0.33,0.11,251.79
11-1987,6.346123,0.27,0.46,0.27,0.00,240.34

merged_df.dtypes

In [70]:
merged_data.head()

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Date,Date,Year,Month
Date_Index,,,,,,,,,,
6-1987,6.283858,NaN,NaN,NaN,NaN,NaN,Jun-87,1-Jun,1987,6
7-1987,6.630484,0.26,0.48,0.26,0.00,318.66,Jul-87,1-Jul,1987,7
8-1987,6.518294,0.52,0.18,0.30,0.22,323.04,Aug-87,1-Aug,1987,8
9-1987,6.127542,0.53,0.17,0.30,0.23,320.16,Sep-87,1-Sep,1987,9
10-1987,6.366409,0.44,0.23,0.33,0.11,251.79,Oct-87,1-Oct,1987,10

In [67]:
#merged_final["Date_Index"]
#.name.unique()

In [33]:
import pandas as pd
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
import pymongo
from pymongo import MongoClient
import os
import json
import datetime

In [34]:
# Setup connection to mongodb
conn = "mongodb://localhost:27017"
client = pymongo.MongoClient(conn)

In [35]:
# Select database and collection to use
#db1 = client.energy_data
#collection = db1.energy_data_values

#db2 = client.investor_sentiment
#collection = db2.investor_sentiment_values

db = client.merged_final
collection = db.merged_final_values

In [36]:
# ====== Inserting Documents ====== #


# Creating a simple Pandas DataFrame
# liste_hello = ['hello1','hello2']
# liste_world = ['world1','world2']

# df = pd.DataFrame(data = {'hello' : liste_hello, 'world': liste_world})


#df = pd.DataFrame.from_dict({'A': {1: datetime.datetime.now()}})
'''
df_to_load_into_JSON_1 = pd.DataFrame.from_dict(energy_data)
df_to_load_into_JSON_1

df_to_load_into_JSON_2 = pd.DataFrame.from_dict(investor_sentiment)
#df_to_load_into_JSON_2
'''

df_to_load_into_JSON = pd.DataFrame.from_dict(merged_final)
df_to_load_into_JSON

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close
Date_Index,,,,,,
7-1987,6.630484,0.260000,0.480000,0.260000,0.000000,318.660000
8-1987,6.518294,0.520000,0.180000,0.300000,0.220000,323.040000
9-1987,6.127542,0.530000,0.170000,0.300000,0.230000,320.160000
10-1987,6.366409,0.440000,0.230000,0.330000,0.110000,251.790000
11-1987,6.346123,0.270000,0.460000,0.270000,0.000000,240.340000
12-1987,7.281541,0.250000,0.490000,0.260000,-0.010000,247.080000
1-1988,7.804136,0.260000,0.450000,0.290000,-0.030000,257.070000
2-1988,7.311849,0.300000,0.510000,0.190000,0.110000,262.460000
3-1988,7.300926,0.450000,0.380000,0.170000,0.280000,258.510000
4-1988,6.453888,0.220000,0.480000,0.300000,-0.080000,261.330000
5-1988,6.394683,0.280000,0.520000,0.200000,0.080000,253.420000
6-1988,6.511855,0.330000,0.440000,0.230000,0.100000,273.780000
7-1988,6.750241,0.230000,0.540000,0.230000,0.000000,272.020000
8-1988,6.992534,0.280000,0.400000,0.320000,-0.040000,259.680000
9-1988,6.344903,0.260000,0.440000,0.300000,-0.040000,271.910000
10-1988,6.591078,0.400000,0.380000,0.220000,0.180000,278.530000
11-1988,6.708190,0.170000,0.440000,0.390000,-0.220000,267.230000
12-1988,7.544911,0.240000,0.540000,0.220000,0.020000,277.720000
1-1989,7.643419,0.320000,0.490000,0.190000,0.130000,293.820000
2-1989,7.233498,0.290000,0.450000,0.260000,0.030000,287.130000
3-1989,7.545703,0.180000,0.420000,0.400000,-0.220000,294.870000
4-1989,6.664216,0.310000,0.400000,0.290000,0.020000,309.640000
5-1989,6.639140,0.480000,0.310000,0.210000,0.270000,321.590000
6-1989,6.697346,0.400000,0.340000,0.260000,0.140000,317.980000
7-1989,6.859659,0.410000,0.250000,0.340000,0.070000,342.150000
8-1989,7.031494,0.450000,0.240000,0.310000,0.140000,350.520000
9-1989,6.484541,0.330000,0.380000,0.290000,0.040000,349.150000
10-1989,6.794031,0.360000,0.330000,0.310000,0.050000,335.060000
11-1989,6.943560,0.270000,0.400000,0.330000,-0.060000,343.970000
12-1989,8.248724,0.350000,0.310000,0.340000,0.010000,353.400000
...,...,...,...,...,...,...
1-2016,9.064412,0.297535,0.302817,0.399648,-0.102113,1882.950000
2-2016,8.237571,0.311947,0.373894,0.314159,-0.002212,1929.800000
3-2016,7.992649,0.271805,0.470588,0.257606,0.014199,2063.949951
4-2016,7.458301,0.273663,0.440329,0.286008,-0.012345,2095.149902
5-2016,7.594760,0.177515,0.528600,0.293886,-0.116371,2090.540039
6-2016,7.945396,0.289125,0.376658,0.334218,-0.045093,2070.770000
7-2016,8.485410,0.312500,0.403409,0.284091,0.028409,2166.580078
8-2016,8.553543,0.294243,0.409382,0.296375,-0.002132,2175.440000
9-2016,7.762231,0.240000,0.388889,0.371111,-0.131111,2171.370117
10-2016,7.664109,0.247549,0.411765,0.340686,-0.093137,2139.429932
11-2016,7.728924,0.498938,0.280255,0.220807,0.278131,2204.720000
12-2016,9.094618,0.455696,0.286920,0.257384,0.198312,2249.920000
1-2017,8.987299,0.315789,0.349282,0.334928,-0.019139,2298.370000
2-2017,7.633252,0.384615,0.292308,0.323077,0.061538,2362.820000
3-2017,8.458327,0.302181,0.323988,0.373832,-0.071651,2361.130000
4-2017,7.461829,0.380488,0.302439,0.317073,0.063415,2387.450000
5-2017,7.818154,0.328571,0.371429,0.300000,0.028571,2404.390000
6-2017,7.980952,0.297143,0.434286,0.268571,0.028572,2440.690000
7-2017,8.429013,0.344595,0.412162,0.243243,0.101352,2477.830000
8-2017,8.313658,0.250000,0.351064,0.398936,-0.148936,2457.590000
9-2017,7.638135,0.333333,0.379310,0.287356,0.045977,2507.040000
10-2017,7.839891,0.396396,0.273273,0.330330,0.066066,2557.150000
11-2017,8.111326,0.359459,0.324324,0.316216,0.043243,2626.070000
12-2017,9.196654,0.526455,0.267196,0.206349,0.320106,2682.620000
1-2018,9.668643,0.454545,0.305195,0.240260,0.214285,2837.540000
2-2018,8.048857,0.446512,0.325581,0.227907,0.218605,2701.330000
3-2018,8.676000,0.319361,0.327345,0.353293,-0.033932,2605.000000
4-2018,7.895465,0.369085,0.375394,0.255521,0.113564,2639.400000
5-2018,8.017006,0.350181,0.386282,0.263538,0.086643,2724.010000
6-2018,8.157678,0.284483,0.307471,0.408046,-0.123563,2699.630000

In [37]:
'''
records1 = json.loads(df_to_load_into_JSON_1.T.to_json()).values()
records1

records2 = json.loads(df_to_load_into_JSON_2.T.to_json()).values()
#records2
'''

records = json.loads(df_to_load_into_JSON.T.to_json()).values()
# records

In [38]:
#db.myCollection.insert(records1)
#db.myCollection.insert(records2)

# Bulk inserting documents. Each row in the DataFrame will be a document in Mongo
# db.insert_data(df.to_dict('records'))
# db.insert_many(df.to_dict('records'))

db.myCollection.insert(records)

print("Data Uploaded!")

Data Uploaded!

/anaconda3/envs/pythondata/lib/python3.6/site-packages/ipykernel/__main__.py:8: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.

In [39]:
# Include this line to make plots interactive
%matplotlib notebook

In [40]:
# Dependencies
import matplotlib.pyplot as plt
import numpy as np

In [41]:
# Begin attempt at visualizations
# make scatterplot of data using ? and ? 

plt.scatter(cost_of_living, environmental_quality, marker="o", facecolors="red", edgecolors="black", 
             alpha=0.75)
plt.legend(loc="lower right")
plt.savefig("../scatter_COL_Environmental.png")

NameError: name 'cost_of_living' is not defined