In [2]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

In [3]:
energy_data = "Resources/Project_2_total_energy_consumption_monthly.csv"
energy_data = pd.read_csv(energy_data)
energy_data.head()

FileNotFoundError: File b'Resources/Project_2_total_energy_consumption_monthly.csv' does not exist

In [ ]:
energy_data = energy_data.rename(columns={"Right": "Month", "Left": "Year"})

In [ ]:
energy_data.head()

In [4]:
energy_data.to_csv("energy_data_convertedDates.csv")
energy_data.dtypes

AttributeError: 'str' object has no attribute 'to_csv'

In [24]:
# set index for energy data 
energy_data["Date_Index"] = energy_data['Month'].map(str) +"-"+ energy_data['Year'].map(str)

In [8]:
investor_sentiment = "Resources/Project_2_investor_sentiment_USA.csv"
investor_sentiment = pd.read_csv(investor_sentiment)
investor_sentiment.head()

,Old Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,Unnamed: 13,coverted Date,Date
0,6/30/2018,0.284483,0.307471,0.408046,1.000000,0.368306,-0.123563,0.382716,0.484453,0.280978,2774.86,2698.67,2699.63,NaN,18-Jun,18-Jun
1,5/31/2018,0.350181,0.386282,0.263538,1.000001,0.341175,0.086643,0.382716,0.484453,0.280978,2742.24,2676.81,2724.01,NaN,18-May,18-May
2,4/30/2018,0.369085,0.375394,0.255521,1.000000,0.326363,0.113564,0.382716,0.484453,0.280978,2717.49,2612.67,2639.40,NaN,18-Apr,18-Apr
3,3/31/2018,0.319361,0.327345,0.353293,0.999999,0.369871,-0.033932,0.382716,0.484453,0.280978,2739.14,2585.89,2605.00,NaN,18-Mar,18-Mar
4,2/28/2018,0.446512,0.325581,0.227907,1.000000,0.478704,0.218605,0.382716,0.484453,0.280978,2754.42,2637.08,2701.33,NaN,18-Feb,18-Feb

In [27]:
# Remake columns for dates of investor data 
# format as date
investor_sentiment['New Date'] = pd.to_datetime(investor_sentiment["Old Date"])

In [28]:
# Create year, month columns
# Create date index
investor_sentiment['Year'], investor_sentiment['Month'] = investor_sentiment['New Date'].dt.year, investor_sentiment['New Date'].dt.month

In [32]:
# create year-month index combo for investor sentiment
investor_sentiment["Date_Index"] = investor_sentiment['Month'].map(str) +"-"+ investor_sentiment['Year'].map(str)

In [33]:
investor_sentiment.head()

,Old Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close,Unnamed: 13,coverted Date,Date,New Date,Year,Month,Date_Index
0,6/30/2018,0.284483,0.307471,0.408046,1.000000,0.368306,-0.123563,0.382716,0.484453,0.280978,2774.86,2698.67,2699.63,NaN,18-Jun,18-Jun,2018-06-30,2018,6,6-2018
1,5/31/2018,0.350181,0.386282,0.263538,1.000001,0.341175,0.086643,0.382716,0.484453,0.280978,2742.24,2676.81,2724.01,NaN,18-May,18-May,2018-05-31,2018,5,5-2018
2,4/30/2018,0.369085,0.375394,0.255521,1.000000,0.326363,0.113564,0.382716,0.484453,0.280978,2717.49,2612.67,2639.40,NaN,18-Apr,18-Apr,2018-04-30,2018,4,4-2018
3,3/31/2018,0.319361,0.327345,0.353293,0.999999,0.369871,-0.033932,0.382716,0.484453,0.280978,2739.14,2585.89,2605.00,NaN,18-Mar,18-Mar,2018-03-31,2018,3,3-2018
4,2/28/2018,0.446512,0.325581,0.227907,1.000000,0.478704,0.218605,0.382716,0.484453,0.280978,2754.42,2637.08,2701.33,NaN,18-Feb,18-Feb,2018-02-28,2018,2,2-2018

In [34]:
investor_sentiment.dtypes

Old Date                             object
Bullish                             float64
Neutral                             float64
Bearish                             float64
Total                               float64
Bullish 8-Week Mov Avg              float64
Bull-Bear Spread                    float64
Bullish Average                     float64
Bullish Average + St. Dev           float64
Bullish Average - St. Dev           float64
S&P 500 Weekly High                 float64
S&P 500 Weekly Low                  float64
S&P 500 Weekly Close                float64
Unnamed: 13                         float64
coverted Date                        object
Date                                 object
New Date                     datetime64[ns]
Year                                  int64
Month                                 int64
Date_Index                           object
dtype: object

In [35]:
energy_data.head()

,MSN,YYYYMM,Value,Column_Order,Description,Unit,Month,Year,Converted Date,Date_Index
0,TETCBUS,198706,6.283858,12,Total Primary Energy Consumption,Quadrillion Btu,6,1987,Jun-87,6-1987
1,TETCBUS,198707,6.630484,12,Total Primary Energy Consumption,Quadrillion Btu,7,1987,Jul-87,7-1987
2,TETCBUS,198708,6.518294,12,Total Primary Energy Consumption,Quadrillion Btu,8,1987,Aug-87,8-1987
3,TETCBUS,198709,6.127542,12,Total Primary Energy Consumption,Quadrillion Btu,9,1987,Sep-87,9-1987
4,TETCBUS,198710,6.366409,12,Total Primary Energy Consumption,Quadrillion Btu,10,1987,Oct-87,10-1987

In [37]:
# rename columns  for energy data
energy_data = energy_data.rename(columns={"Value": "Total Primary Energy Consumption (Quadrillion BTUs)"})

In [39]:
# drop columns for energy data 
energy_data_refined = energy_data.drop(columns=["MSN", "YYYYMM", "Column_Order", "Unit", "Year", "Month", "Description", "Converted Date"])

In [41]:
# set index for energy data
energy_indexed= energy_data_refined.set_index("Date_Index")
energy_indexed.head()

            Total Primary Energy Consumption (Quadrillion BTUs)
Date_Index
6-1987                                               6.283858
7-1987                                               6.630484
8-1987                                               6.518294
9-1987                                               6.127542
10-1987                                              6.366409

In [42]:
# drop columns for investor data

investor_sentiment_refined = investor_sentiment.drop(columns=["Old Date", "Total", "Bullish 8-Week Mov Avg", "Bullish Average", "Bullish Average + St. Dev", "Bullish Average - St. Dev", "S&P 500 Weekly High", "S&P 500 Weekly Low", "Unnamed: 13"])

In [43]:
# rename columns for investor data
investor_sentiment_renamed =investor_sentiment_refined.rename(columns={"Bullish": "Bullish Sentiment", "Neutral": "Neutral Sentiment", "Bearish": "Bearish Sentiment", "coverted Date": "Date"})

In [44]:
# set index for investor data

investor_indexed = investor_sentiment_renamed.set_index("Date_Index")
investor_indexed.head()

,Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Date,Date,New Date,Year,Month
Date_Index,,,,,,,,,,
6-2018,0.284483,0.307471,0.408046,-0.123563,2699.63,18-Jun,18-Jun,2018-06-30,2018,6
5-2018,0.350181,0.386282,0.263538,0.086643,2724.01,18-May,18-May,2018-05-31,2018,5
4-2018,0.369085,0.375394,0.255521,0.113564,2639.40,18-Apr,18-Apr,2018-04-30,2018,4
3-2018,0.319361,0.327345,0.353293,-0.033932,2605.00,18-Mar,18-Mar,2018-03-31,2018,3
2-2018,0.446512,0.325581,0.227907,0.218605,2701.33,18-Feb,18-Feb,2018-02-28,2018,2

In [46]:
# merge data sets on date index 
merged_data = pd.merge(energy_indexed, investor_indexed, on="Date_Index")
merged_data.head(20)
#merged_data

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Date,Date,New Date,Year,Month
Date_Index,,,,,,,,,,,
6-1987,6.283858,NaN,NaN,NaN,NaN,NaN,Jun-87,1-Jun,1987-06-30,1987,6
7-1987,6.630484,0.26,0.48,0.26,0.00,318.66,Jul-87,1-Jul,1987-07-31,1987,7
8-1987,6.518294,0.52,0.18,0.30,0.22,323.04,Aug-87,1-Aug,1987-08-31,1987,8
9-1987,6.127542,0.53,0.17,0.30,0.23,320.16,Sep-87,1-Sep,1987-09-30,1987,9
10-1987,6.366409,0.44,0.23,0.33,0.11,251.79,Oct-87,1-Oct,1987-10-31,1987,10
11-1987,6.346123,0.27,0.46,0.27,0.00,240.34,Nov-87,1-Nov,1987-11-30,1987,11
12-1987,7.281541,0.25,0.49,0.26,-0.01,247.08,Dec-87,1-Dec,1987-12-31,1987,12
1-1988,7.804136,0.26,0.45,0.29,-0.03,257.07,Jan-88,1-Jan,1988-01-31,1988,1
2-1988,7.311849,0.30,0.51,0.19,0.11,262.46,Feb-88,1-Feb,1988-02-29,1988,2
3-1988,7.300926,0.45,0.38,0.17,0.28,258.51,Mar-88,1-Mar,1988-03-31,1988,3
4-1988,6.453888,0.22,0.48,0.30,-0.08,261.33,Apr-88,1-Apr,1988-04-30,1988,4
5-1988,6.394683,0.28,0.52,0.20,0.08,253.42,May-88,1-May,1988-05-31,1988,5
6-1988,6.511855,0.33,0.44,0.23,0.10,273.78,Jun-88,1-Jun,1988-06-30,1988,6
7-1988,6.750241,0.23,0.54,0.23,0.00,272.02,Jul-88,1-Jul,1988-07-31,1988,7
8-1988,6.992534,0.28,0.40,0.32,-0.04,259.68,Aug-88,1-Aug,1988-08-31,1988,8
9-1988,6.344903,0.26,0.44,0.30,-0.04,271.91,Sep-88,1-Sep,1988-09-30,1988,9
10-1988,6.591078,0.40,0.38,0.22,0.18,278.53,Oct-88,1-Oct,1988-10-31,1988,10
11-1988,6.708190,0.17,0.44,0.39,-0.22,267.23,Nov-88,1-Nov,1988-11-30,1988,11
12-1988,7.544911,0.24,0.54,0.22,0.02,277.72,Dec-88,1-Dec,1988-12-31,1988,12
1-1989,7.643419,0.32,0.49,0.19,0.13,293.82,Jan-89,1-Jan,1989-01-31,1989,1

In [47]:
merged_data.describe()

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Year,Month
count,373.000000,372.000000,372.000000,372.000000,372.000000,372.000000,373.000000,373.00000
mean,7.850449,0.385664,0.312137,0.302196,0.083468,1114.300242,2002.458445,6.49866
std,0.681195,0.101233,0.082521,0.095346,0.178518,606.682673,8.994115,3.45215
min,6.127542,0.170000,0.106700,0.066700,-0.380000,240.340000,1987.000000,1.00000
25%,7.471880,0.308196,0.257675,0.229875,-0.042548,511.210000,1995.000000,4.00000
50%,7.809119,0.380000,0.312250,0.296409,0.075600,1123.905000,2002.000000,6.00000
75%,8.312785,0.450000,0.370000,0.364741,0.210000,1399.082500,2010.000000,9.00000
max,9.668643,0.714300,0.540000,0.610000,0.628600,2837.540000,2018.000000,12.00000

In [48]:
merged_data.dtypes

Total Primary Energy Consumption (Quadrillion BTUs)           float64
Bullish Sentiment                                             float64
Neutral Sentiment                                             float64
Bearish Sentiment                                             float64
Bull-Bear Spread                                              float64
S&P 500 Weekly Close                                          float64
Date                                                           object
Date                                                           object
New Date                                               datetime64[ns]
Year                                                            int64
Month                                                           int64
dtype: object

In [49]:
# drop columns for merged data

merged_data = merged_data.drop(columns=["Date", "Date", "New Date", ])

In [50]:
merged_data.head()

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Year,Month
Date_Index,,,,,,,,
6-1987,6.283858,NaN,NaN,NaN,NaN,NaN,1987,6
7-1987,6.630484,0.26,0.48,0.26,0.00,318.66,1987,7
8-1987,6.518294,0.52,0.18,0.30,0.22,323.04,1987,8
9-1987,6.127542,0.53,0.17,0.30,0.23,320.16,1987,9
10-1987,6.366409,0.44,0.23,0.33,0.11,251.79,1987,10

In [51]:
merged_data

,Total Primary Energy Consumption (Quadrillion BTUs),Bullish Sentiment,Neutral Sentiment,Bearish Sentiment,Bull-Bear Spread,S&P 500 Weekly Close,Year,Month
Date_Index,,,,,,,,
6-1987,6.283858,NaN,NaN,NaN,NaN,NaN,1987,6
7-1987,6.630484,0.260000,0.480000,0.260000,0.000000,318.660000,1987,7
8-1987,6.518294,0.520000,0.180000,0.300000,0.220000,323.040000,1987,8
9-1987,6.127542,0.530000,0.170000,0.300000,0.230000,320.160000,1987,9
10-1987,6.366409,0.440000,0.230000,0.330000,0.110000,251.790000,1987,10
11-1987,6.346123,0.270000,0.460000,0.270000,0.000000,240.340000,1987,11
12-1987,7.281541,0.250000,0.490000,0.260000,-0.010000,247.080000,1987,12
1-1988,7.804136,0.260000,0.450000,0.290000,-0.030000,257.070000,1988,1
2-1988,7.311849,0.300000,0.510000,0.190000,0.110000,262.460000,1988,2
3-1988,7.300926,0.450000,0.380000,0.170000,0.280000,258.510000,1988,3
4-1988,6.453888,0.220000,0.480000,0.300000,-0.080000,261.330000,1988,4
5-1988,6.394683,0.280000,0.520000,0.200000,0.080000,253.420000,1988,5
6-1988,6.511855,0.330000,0.440000,0.230000,0.100000,273.780000,1988,6
7-1988,6.750241,0.230000,0.540000,0.230000,0.000000,272.020000,1988,7
8-1988,6.992534,0.280000,0.400000,0.320000,-0.040000,259.680000,1988,8
9-1988,6.344903,0.260000,0.440000,0.300000,-0.040000,271.910000,1988,9
10-1988,6.591078,0.400000,0.380000,0.220000,0.180000,278.530000,1988,10
11-1988,6.708190,0.170000,0.440000,0.390000,-0.220000,267.230000,1988,11
12-1988,7.544911,0.240000,0.540000,0.220000,0.020000,277.720000,1988,12
1-1989,7.643419,0.320000,0.490000,0.190000,0.130000,293.820000,1989,1
2-1989,7.233498,0.290000,0.450000,0.260000,0.030000,287.130000,1989,2
3-1989,7.545703,0.180000,0.420000,0.400000,-0.220000,294.870000,1989,3
4-1989,6.664216,0.310000,0.400000,0.290000,0.020000,309.640000,1989,4
5-1989,6.639140,0.480000,0.310000,0.210000,0.270000,321.590000,1989,5
6-1989,6.697346,0.400000,0.340000,0.260000,0.140000,317.980000,1989,6
7-1989,6.859659,0.410000,0.250000,0.340000,0.070000,342.150000,1989,7
8-1989,7.031494,0.450000,0.240000,0.310000,0.140000,350.520000,1989,8
9-1989,6.484541,0.330000,0.380000,0.290000,0.040000,349.150000,1989,9
10-1989,6.794031,0.360000,0.330000,0.310000,0.050000,335.060000,1989,10
11-1989,6.943560,0.270000,0.400000,0.330000,-0.060000,343.970000,1989,11
...,...,...,...,...,...,...,...,...
1-2016,9.064412,0.297535,0.302817,0.399648,-0.102113,1882.950000,2016,1
2-2016,8.237571,0.311947,0.373894,0.314159,-0.002212,1929.800000,2016,2
3-2016,7.992649,0.271805,0.470588,0.257606,0.014199,2063.949951,2016,3
4-2016,7.458301,0.273663,0.440329,0.286008,-0.012345,2095.149902,2016,4
5-2016,7.594760,0.177515,0.528600,0.293886,-0.116371,2090.540039,2016,5
6-2016,7.945396,0.289125,0.376658,0.334218,-0.045093,2070.770000,2016,6
7-2016,8.485410,0.312500,0.403409,0.284091,0.028409,2166.580078,2016,7
8-2016,8.553543,0.294243,0.409382,0.296375,-0.002132,2175.440000,2016,8
9-2016,7.762231,0.240000,0.388889,0.371111,-0.131111,2171.370117,2016,9
10-2016,7.664109,0.247549,0.411765,0.340686,-0.093137,2139.429932,2016,10
11-2016,7.728924,0.498938,0.280255,0.220807,0.278131,2204.720000,2016,11
12-2016,9.094618,0.455696,0.286920,0.257384,0.198312,2249.920000,2016,12
1-2017,8.987299,0.315789,0.349282,0.334928,-0.019139,2298.370000,2017,1
2-2017,7.633252,0.384615,0.292308,0.323077,0.061538,2362.820000,2017,2
3-2017,8.458327,0.302181,0.323988,0.373832,-0.071651,2361.130000,2017,3
4-2017,7.461829,0.380488,0.302439,0.317073,0.063415,2387.450000,2017,4
5-2017,7.818154,0.328571,0.371429,0.300000,0.028571,2404.390000,2017,5
6-2017,7.980952,0.297143,0.434286,0.268571,0.028572,2440.690000,2017,6
7-2017,8.429013,0.344595,0.412162,0.243243,0.101352,2477.830000,2017,7
8-2017,8.313658,0.250000,0.351064,0.398936,-0.148936,2457.590000,2017,8
9-2017,7.638135,0.333333,0.379310,0.287356,0.045977,2507.040000,2017,9
10-2017,7.839891,0.396396,0.273273,0.330330,0.066066,2557.150000,2017,10
11-2017,8.111326,0.359459,0.324324,0.316216,0.043243,2626.070000,2017,11
12-2017,9.196654,0.526455,0.267196,0.206349,0.320106,2682.620000,2017,12
1-2018,9.668643,0.454545,0.305195,0.240260,0.214285,2837.540000,2018,1
2-2018,8.048857,0.446512,0.325581,0.227907,0.218605,2701.330000,2018,2
3-2018,8.676000,0.319361,0.327345,0.353293,-0.033932,2605.000000,2018,3
4-2018,7.895465,0.369085,0.375394,0.255521,0.113564,2639.400000,2018,4
5-2018,8.017006,0.350181,0.386282,0.263538,0.086643,2724.010000,2018,5
6-2018,8.157678,0.284483,0.307471,0.408046,-0.123563,2699.630000,2018,6