In [1]:
import pandas as pd
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
import pymongo
from pymongo import MongoClient
import os
import json
import datetime

In [2]:
sentiment = pd.read_csv('AAII-AAII_SENTIMENT.csv')
sentiment

,Date,Bullish,Neutral,Bearish,Total,Bullish 8-Week Mov Avg,Bull-Bear Spread,Bullish Average,Bullish Average + St. Dev,Bullish Average - St. Dev,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close
0,2018-10-11,0.306061,0.339394,0.354545,1.000000,0.376000,-0.048484,0.382716,0.484453,0.280978,2939.86,2784.86,2785.68
1,2018-10-04,0.456621,0.292237,0.251142,1.000000,0.382955,0.205479,0.382716,0.484453,0.280978,2939.86,2903.28,2925.51
2,2018-09-27,0.362205,0.326772,0.311024,1.000001,0.371332,0.051181,0.382716,0.484453,0.280978,2940.91,2903.28,2905.97
3,2018-09-20,0.320423,0.359155,0.320423,1.000001,0.362445,0.000000,0.382716,0.484453,0.280978,2912.36,2879.20,2907.95
4,2018-09-13,0.320896,0.350746,0.328358,1.000000,0.361794,-0.007462,0.382716,0.484453,0.280978,2894.65,2864.12,2888.92
5,2018-09-06,0.422222,0.314815,0.262963,1.000000,0.365011,0.159259,0.382716,0.484453,0.280978,2916.50,2876.92,2888.60
6,2018-08-30,0.434959,0.321138,0.243902,0.999999,0.366047,0.191057,0.382716,0.484453,0.280978,2916.50,2854.03,2914.04
7,2018-08-23,0.384615,0.344729,0.270655,0.999999,0.346496,0.113960,0.382716,0.484453,0.280978,2873.23,2802.49,2861.82
8,2018-08-16,0.361702,0.347518,0.290780,1.000000,0.333979,0.070922,0.382716,0.484453,0.280978,2862.48,2802.49,2818.37
9,2018-08-09,0.363636,0.326019,0.310345,1.000000,0.337165,0.053291,0.382716,0.484453,0.280978,2863.43,2796.34,2857.70
10,2018-08-02,0.291105,0.388140,0.320755,1.000000,0.347686,-0.029650,0.382716,0.484453,0.280978,2848.03,2798.11,2813.36
11,2018-07-26,0.315217,0.415761,0.269022,1.000000,0.359962,0.046195,0.382716,0.484453,0.280978,2848.03,2795.14,2846.07
12,2018-07-19,0.346633,0.403990,0.249377,1.000000,0.364332,0.097256,0.382716,0.484453,0.280978,2816.76,2770.77,2815.62
13,2018-07-12,0.430508,0.277966,0.291525,0.999999,0.369206,0.138983,0.382716,0.484453,0.280978,2795.58,2711.16,2774.02
14,2018-07-05,0.278552,0.328691,0.392758,1.000001,0.361237,-0.114206,0.382716,0.484453,0.280978,2746.09,2691.99,2713.22
15,2018-06-28,0.284483,0.307471,0.408046,1.000000,0.368306,-0.123563,0.382716,0.484453,0.280978,2774.86,2698.67,2699.63
16,2018-06-21,0.387187,0.350975,0.261838,1.000000,0.368239,0.125349,0.382716,0.484453,0.280978,2791.47,2743.19,2767.32
17,2018-06-14,0.447802,0.335165,0.217033,1.000000,0.365977,0.230769,0.382716,0.484453,0.280978,2791.47,2748.46,2775.63
18,2018-06-07,0.389313,0.343511,0.267176,1.000000,0.357231,0.122137,0.382716,0.484453,0.280978,2772.39,2700.68,2772.35
19,2018-05-31,0.350181,0.386282,0.263538,1.000001,0.341175,0.086643,0.382716,0.484453,0.280978,2742.24,2676.81,2724.01
20,2018-05-24,0.385621,0.362745,0.251634,1.000000,0.337274,0.133987,0.382716,0.484453,0.280978,2742.24,2709.18,2733.29
21,2018-05-17,0.366755,0.427441,0.205805,1.000001,0.328991,0.160950,0.382716,0.484453,0.280978,2742.10,2674.14,2722.46
22,2018-05-10,0.335106,0.409574,0.255319,0.999999,0.324690,0.079787,0.382716,0.484453,0.280978,2701.27,2594.62,2697.79
23,2018-05-03,0.283951,0.413580,0.302469,1.000000,0.328854,-0.018518,0.382716,0.484453,0.280978,2682.87,2612.67,2635.67
24,2018-04-26,0.369085,0.375394,0.255521,1.000000,0.326363,0.113564,0.382716,0.484453,0.280978,2717.49,2612.67,2639.40
25,2018-04-19,0.377834,0.329975,0.292191,1.000000,0.326832,0.085643,0.382716,0.484453,0.280978,2717.49,2639.25,2708.64
26,2018-04-12,0.260870,0.311594,0.427536,1.000000,0.335417,-0.166666,0.382716,0.484453,0.280978,2672.08,2573.61,2642.19
27,2018-04-05,0.318966,0.314655,0.366379,1.000000,0.363457,-0.047413,0.382716,0.484453,0.280978,2674.78,2553.80,2644.69
28,2018-03-29,0.319361,0.327345,0.353293,0.999999,0.369871,-0.033932,0.382716,0.484453,0.280978,2739.14,2585.89,2605.00
29,2018-03-22,0.332344,0.382789,0.284866,0.999999,0.385915,0.047478,0.382716,0.484453,0.280978,2777.11,2694.59,2711.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1601,1988-01-29,0.260000,0.450000,0.290000,1.000000,0.280000,-0.030000,0.384907,0.488293,0.281522,257.07,249.38,257.07
1602,1988-01-22,0.210000,0.480000,0.310000,1.000000,0.278750,-0.100000,0.384907,0.488293,0.281522,251.88,242.63,246.50
1603,1988-01-15,0.340000,0.400000,0.260000,1.000000,0.286250,0.080000,0.384907,0.488293,0.281522,252.05,245.42,252.05
1604,1988-01-08,0.340000,0.460000,0.200000,1.000000,0.292500,0.140000,0.384907,0.488293,0.281522,261.07,243.40,243.40
1605,1987-12-31,0.250000,0.490000,0.260000,1.000000,0.288750,-0.010000,0.384907,0.488293,0.281522,247.86,244.59,247.08
1606,1987-12-24,0.280000,0.520000,0.200000,1.000000,0.316250,0.080000,0.384907,0.488293,0.281522,253.16,249.54,252.02
1607,1987-12-18,0.330000,0.400000,0.270000,1.000000,0.336250,0.060000,0.384907,0.488293,0.281522,249.16,242.19,249.16
1608,1987-12-11,0.230000,0.450000,0.320000,1.000000,0.343750,-0.090000,0.384907,0.488293,0.281522,238.89,228.76,235.32
1609,1987-12-04,0.250000,0.330000,0.420000,1.000000,0.361250,-0.170000,0.384907,0.488293,0.281522,233.45,223.92,223.92
1610,1987-11-27,0.270000,0.460000,0.270000,1.000000,0.387500,0.000000,0.384907,0.488293,0.281522,246.39,240.34,240.34
1611,1987-11-20,0.390000,0.420000,0.190000,1.000000,0.408750,0.200000,0.384907,0.488293,0.281522,246.76,240.05,242.00
1612,1987-11-13,0.310000,0.410000,0.280000,1.000000,0.426250,0.030000,0.384907,0.488293,0.281522,248.52,239.00,245.64
1613,1987-11-06,0.470000,0.310000,0.220000,1.000000,0.462500,0.250000,0.384907,0.488293,0.281522,255.75,248.31,250.41
1614,1987-10-30,0.440000,0.230000,0.330000,1.000000,0.466250,0.110000,0.384907,0.488293,0.281522,251.79,227.67,251.79
1615,1987-10-23,0.390000,0.300000,0.310000,1.000000,0.463750,0.080000,0.384907,0.488293,0.281522,258.39,224.84,248.22
1616,1987-10-16,0.370000,0.300000,0.330000,1.000000,0.480000,0.040000,0.384907,0.488293,0.281522,314.52,282.70,282.70
1617,1987-10-09,0.460000,0.390000,0.150000,1.000000,0.516250,0.310000,0.384907,0.488293,0.281522,328.08,311.07,311.07
1618,1987-10-02,0.440000,0.260000,0.300000,1.000000,0.515000,0.140000,0.384907,0.488293,0.281522,328.07,321.69,328.07
1619,1987-09-25,0.530000,0.170000,0.300000,1.000000,0.530000,0.230000,0.384907,0.488293,0.281522,321.19,310.54,320.16
1620,1987-09-18,0.600000,0.290000,0.110000,1.000000,0.496250,0.490000,0.384907,0.488293,0.281522,323.08,314.86,314.86
1621,1987-09-11,0.500000,0.230000,0.270000,1.000000,0.466250,0.230000,0.384907,0.488293,0.281522,321.98,313.56,321.98
1622,1987-09-04,0.420000,0.170000,0.410000,1.000000,NaN,0.010000,0.386014,0.489178,0.282850,329.79,316.70,316.70
1623,1987-08-28,0.520000,0.180000,0.300000,1.000000,NaN,0.220000,0.386014,0.489178,0.282850,331.38,323.04,323.04
1624,1987-08-21,0.660000,0.280000,0.060000,1.000000,NaN,0.600000,0.386014,0.489178,0.282850,335.90,329.25,335.90
1625,1987-08-14,0.450000,0.350000,0.200000,1.000000,NaN,0.250000,0.386014,0.489178,0.282850,334.65,323.00,333.99
1626,1987-08-07,0.560000,0.150000,0.290000,1.000000,NaN,0.270000,0.386014,0.489178,0.282850,323.00,316.23,323.00
1627,1987-07-31,0.260000,0.480000,0.260000,1.000000,NaN,0.000000,0.386014,0.489178,0.282850,318.66,310.65,318.66
1628,1987-07-24,0.360000,0.500000,0.140000,1.000000,NaN,0.220000,0.386014,0.489178,0.282850,311.39,307.81,309.27
1629,1987-07-17,NaN,NaN,NaN,NaN,NaN,NaN,0.386014,0.489178,0.282850,314.59,307.63,314.59
1630,1987-06-26,NaN,NaN,NaN,NaN,NaN,NaN,0.386014,0.489178,0.282850,NaN,NaN,NaN

In [3]:
energy_df = pd.read_csv('EIA-SEDS_TETCB_US_A.csv')
energy_df.head()

         Date       Value
0  2016-12-31  97314710.0
1  2015-12-31  97410967.0
2  2014-12-31  98391552.0
3  2013-12-31  97223138.0
4  2012-12-31  94454840.0

In [4]:
# Create engine using the `demographics.sqlite` database file
engine = create_engine("sqlite:///../Resources/demographics.sqlite")

In [5]:
# Import SQL Alchemy
from sqlalchemy import create_engine

# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float

In [6]:
from odo import odo
#>>> odo(source, target)  # load source into target

C:\Users\Shail\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\Shail\Anaconda3\lib\site-packages\odo\backends\pandas.py:102: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))

In [7]:
#odo(energy_df, 'mongodb://hostname/db::collection') # Dump Mongo to DataFrame
odo(energy_df,'mongodb://localhost:27017/test_db::test_collection')

AttributeError: 'DiGraph' object has no attribute 'edge'

In [8]:
from pymongo import MongoClient
client = MongoClient()

In [9]:
client = MongoClient('localhost', 27017)

In [10]:
client = MongoClient('mongodb://localhost:27017/')

In [ ]:
odo(energy_df, 'test.csv')

In [11]:
# Setup connection to mongodb
conn = "mongodb://localhost:27017"
client = pymongo.MongoClient(conn)

In [12]:
# Select database and collection to use
db = client.test
collection = db.test_stuff

In [14]:
# ====== Inserting Documents ====== #


# Creating a simple Pandas DataFrame
# liste_hello = ['hello1','hello2']
# liste_world = ['world1','world2']

# df = pd.DataFrame(data = {'hello' : liste_hello, 'world': liste_world})


#df = pd.DataFrame.from_dict({'A': {1: datetime.datetime.now()}})
df = pd.DataFrame.from_dict(energy_df)
df

          Date        Value
0   2016-12-31   97314710.0
1   2015-12-31   97410967.0
2   2014-12-31   98391552.0
3   2013-12-31   97223138.0
4   2012-12-31   94454840.0
5   2011-12-31   96897848.0
6   2010-12-31   97543976.0
7   2009-12-31   94093700.0
8   2008-12-31   98861525.0
9   2007-12-31  100991264.0
10  2006-12-31   99447077.0
11  2005-12-31  100183716.0
12  2004-12-31  100097583.0
13  2003-12-31   97915776.0
14  2002-12-31   97648367.0
15  2001-12-31   96143798.0
16  2000-12-31   98807639.0
17  1999-12-31   96628206.0
18  1998-12-31   95029805.0
19  1997-12-31   94748492.0
20  1996-12-31   94089700.0
21  1995-12-31   91093327.0
22  1994-12-31   89113599.0
23  1993-12-31   87393191.0
24  1992-12-31   85787680.0
25  1991-12-31   84434783.0
26  1990-12-31   84506007.0
27  1989-12-31   84776434.0
28  1988-12-31   82760410.0
29  1987-12-31   79005567.0
30  1986-12-31   76639363.0
31  1985-12-31   76464077.0
32  1984-12-31   76571095.0
33  1983-12-31   72934367.0
34  1982-12-31   73058784.0
35  1981-12-31   76141756.0
36  1980-12-31   78092506.0
37  1979-12-31   80882446.0
38  1978-12-31   80021769.0
39  1977-12-31   77988301.0
40  1976-12-31   76002450.0
41  1975-12-31   71986573.0
42  1974-12-31   73947572.0
43  1973-12-31   75755267.0
44  1972-12-31   72705040.0
45  1971-12-31   69186565.0
46  1970-12-31   67741611.0
47  1969-12-31   65596682.0
48  1968-12-31   62414722.0
49  1967-12-31   58926572.0
50  1966-12-31   57026015.0
51  1965-12-31   54027593.0
52  1964-12-31   51826046.0
53  1963-12-31   49661147.0
54  1962-12-31   47824415.0
55  1961-12-31   45731168.0
56  1960-12-31   45079292.0

In [15]:
records = json.loads(df.T.to_json()).values()
records

dict_values([{'Date': '2016-12-31', 'Value': 97314710.0}, {'Date': '2015-12-31', 'Value': 97410967.0}, {'Date': '2014-12-31', 'Value': 98391552.0}, {'Date': '2013-12-31', 'Value': 97223138.0}, {'Date': '2012-12-31', 'Value': 94454840.0}, {'Date': '2011-12-31', 'Value': 96897848.0}, {'Date': '2010-12-31', 'Value': 97543976.0}, {'Date': '2009-12-31', 'Value': 94093700.0}, {'Date': '2008-12-31', 'Value': 98861525.0}, {'Date': '2007-12-31', 'Value': 100991264.0}, {'Date': '2006-12-31', 'Value': 99447077.0}, {'Date': '2005-12-31', 'Value': 100183716.0}, {'Date': '2004-12-31', 'Value': 100097583.0}, {'Date': '2003-12-31', 'Value': 97915776.0}, {'Date': '2002-12-31', 'Value': 97648367.0}, {'Date': '2001-12-31', 'Value': 96143798.0}, {'Date': '2000-12-31', 'Value': 98807639.0}, {'Date': '1999-12-31', 'Value': 96628206.0}, {'Date': '1998-12-31', 'Value': 95029805.0}, {'Date': '1997-12-31', 'Value': 94748492.0}, {'Date': '1996-12-31', 'Value': 94089700.0}, {'Date': '1995-12-31', 'Value': 91093327.0}, {'Date': '1994-12-31', 'Value': 89113599.0}, {'Date': '1993-12-31', 'Value': 87393191.0}, {'Date': '1992-12-31', 'Value': 85787680.0}, {'Date': '1991-12-31', 'Value': 84434783.0}, {'Date': '1990-12-31', 'Value': 84506007.0}, {'Date': '1989-12-31', 'Value': 84776434.0}, {'Date': '1988-12-31', 'Value': 82760410.0}, {'Date': '1987-12-31', 'Value': 79005567.0}, {'Date': '1986-12-31', 'Value': 76639363.0}, {'Date': '1985-12-31', 'Value': 76464077.0}, {'Date': '1984-12-31', 'Value': 76571095.0}, {'Date': '1983-12-31', 'Value': 72934367.0}, {'Date': '1982-12-31', 'Value': 73058784.0}, {'Date': '1981-12-31', 'Value': 76141756.0}, {'Date': '1980-12-31', 'Value': 78092506.0}, {'Date': '1979-12-31', 'Value': 80882446.0}, {'Date': '1978-12-31', 'Value': 80021769.0}, {'Date': '1977-12-31', 'Value': 77988301.0}, {'Date': '1976-12-31', 'Value': 76002450.0}, {'Date': '1975-12-31', 'Value': 71986573.0}, {'Date': '1974-12-31', 'Value': 73947572.0}, {'Date': '1973-12-31', 'Value': 75755267.0}, {'Date': '1972-12-31', 'Value': 72705040.0}, {'Date': '1971-12-31', 'Value': 69186565.0}, {'Date': '1970-12-31', 'Value': 67741611.0}, {'Date': '1969-12-31', 'Value': 65596682.0}, {'Date': '1968-12-31', 'Value': 62414722.0}, {'Date': '1967-12-31', 'Value': 58926572.0}, {'Date': '1966-12-31', 'Value': 57026015.0}, {'Date': '1965-12-31', 'Value': 54027593.0}, {'Date': '1964-12-31', 'Value': 51826046.0}, {'Date': '1963-12-31', 'Value': 49661147.0}, {'Date': '1962-12-31', 'Value': 47824415.0}, {'Date': '1961-12-31', 'Value': 45731168.0}, {'Date': '1960-12-31', 'Value': 45079292.0}])

In [16]:
db.myCollection.insert(records)
# Bulk inserting documents. Each row in the DataFrame will be a document in Mongo
# db.insert_data(df.to_dict('records'))
# db.insert_many(df.to_dict('records'))

print("Data Uploaded!")

Data Uploaded!

C:\Users\Shail\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  """Entry point for launching an IPython kernel.